services:
  api:
    image: dantor20/meli-products-api:latest
    container_name: meli-products-api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped